name: Build and Test

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
    - 'doc/**'
    - 'docs/**'
    - 'readme.md'

  pull_request:
    branches: [ master, dev ]
    paths-ignore:
    - 'doc/**'
    - 'docs/**'
    - 'readme.md'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
    - name: Setup .NET 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.*
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*


    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --configuration Release --verbosity normal
